server:
  port: 8080
spring:
  webflux:
    base-path: /autenticacion
  application:
    name: "autenticacion"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  adapters:
    r2dbc:
      host: localhost
      port: "5432"
      database: "crediya"
      schema: "autenticacion"
      username: "postgres"
      password: "12345678"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
jwt:
  secret: d8206c23d2708ed420f4096768adde814a623e757120184edc98fc74f36951ade397ea9a809b576bf543dc47e7df26d0e723749334c35267507ef755e8f0caaa
  expiration: 3600000
