server:
  port: 8080
spring:
  webflux:
    base-path: /autenticacion
  application:
    name: "autenticacion"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  adapters:
    r2dbc:
      host: localhost
      port: "5432"
      database: "crediya"
      schema: "autenticacion"
      username: "postgres"
      password: "12345678"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
jwt:
  secret: 8a9b7c6d5e4f3a2b1a0f9e8d7c6b5a4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a
  expiration: 3600000
